[package]
name = "Stc-Bridge-Move"
version = "0.0.1"

[addresses]
StarcoinFramework = "0x1"
std = "0x1"
Bridge = "0x34aa399de7b439fd802daa9afefe0e9d"

[dependencies]
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "v12" }

[dev-dependencies]
UnitTest = { git = "https://github.com/starcoinorg/starcoin-framework.git", subdir = "unit-test", rev = "v12" }